-- AlterTable: Add Phase 1 fields to CareRecipient
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "emergencyContactFax" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensorySound" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensoryLight" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensoryTaste" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensoryTouch" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensorySmell" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "sensoryOther" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "obsessionPast" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "obsessionCurrent" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "selfHarmContent" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "aggressionContent" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "panicContent" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyOuting" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyTv" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyMusic" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyBook" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyInterpersonal" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyInterestScope" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyFoodPreference" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hobbyOther" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationMorning" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationNoon" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationEvening" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationBedtime" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationOtherTime" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationTimeSpecific" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "medicationNote" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "prnMedicationContent" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "prnMedicationTiming" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "prnMedicationMemo" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "seizureTimePattern" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "seizureHistoryNote" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "hasTopicalMedication" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "topicalMedicationNote" TEXT;
ALTER TABLE "CareRecipient" ADD COLUMN IF NOT EXISTS "personality" TEXT;

-- AlterTable: Add Phase 1 fields to Assessment
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientGender" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientDisabilityName" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientSupportLevel" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientHandbook" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientFacility" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recipientAddress" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "serviceManager" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "homeManager" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "dayService" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "familyStatus" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "recentStatus" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "socialRelationship" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "socialRules" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commExpressionMethods" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commExpressionContent" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commExpressionOther" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commUnderstandMethods" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commCognitionLevels" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "commCognitionOther" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlEating3Level" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlEatingSupport" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlToiletSmall3Level" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlToiletSmallSupport" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlToiletLarge3Level" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlToiletLargeSupport" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlBathing3Level" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlBathingSupport" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlDressing3Level" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlDressingSupport" TEXT;
ALTER TABLE "Assessment" ADD COLUMN IF NOT EXISTS "adlOther3Level" TEXT;
